// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = PortfolioSlice | AboutSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: The title of the page
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief description of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Item in *Portfolio → Items*
 */
export interface PortfolioSliceDefaultItem {
  /**
   * Title field in *Portfolio → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Project title
   * - **API ID Path**: portfolio.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Portfolio → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Project description
   * - **API ID Path**: portfolio.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Portfolio → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: Project image
   * - **API ID Path**: portfolio.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Link field in *Portfolio → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Project link
   * - **API ID Path**: portfolio.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Technologies field in *Portfolio → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Technologies used (comma separated)
   * - **API ID Path**: portfolio.items[].technologies
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  technologies: prismic.RichTextField;
}

/**
 * Default variation for Portfolio Slice
 *
 * - **API ID**: `default`
 * - **Description**: Portfolio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export interface PortfolioSliceDefault {
  variation: "default";
  version: string;
  items: PortfolioSliceDefaultItem[];
  primary: {
    /**
     * Heading field in *Portfolio → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: Portfolio section heading
     * - **API ID Path**: portfolio.primary.heading
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    heading: prismic.TitleField;

    /**
     * Description field in *Portfolio → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Portfolio section description
     * - **API ID Path**: portfolio.primary.description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField;
  };
}

/**
 * Portfolio Slice
 *
 * - **API ID**: `portfolio`
 * - **Description**: Portfolio
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PortfolioSlice = PortfolioSliceDefault;

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export interface AboutSliceDefault {
  variation: "default";
  version: string;
  items: never;
  primary: {
    /**
     * Heading field in *About → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: About section heading
     * - **API ID Path**: about.primary.heading
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    heading: prismic.TitleField;

    /**
     * Description field in *About → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: About description
     * - **API ID Path**: about.primary.description
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    description: prismic.RichTextField;

    /**
     * Avatar field in *About → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: Profile image
     * - **API ID Path**: about.primary.avatar
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    avatar: prismic.ImageField<never>;

    /**
     * Skills field in *About → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: Skills and technologies
     * - **API ID Path**: about.primary.skills
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    skills: prismic.RichTextField;

    /**
     * Resume Link field in *About → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: Link to resume/CV
     * - **API ID Path**: about.primary.resume_link
     * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
     */
    resume_link: prismic.LinkField;
  };
}

/**
 * About Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = AboutSliceDefault;

export type AllDocumentTypes = HomepageDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PortfolioSlice,
      PortfolioSliceDefault,
      PortfolioSliceDefaultItem,
      AboutSlice,
      AboutSliceDefault,
      AllDocumentTypes,
    };
  }
}